name: 'odoo'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 3

  odoo:
    image: odoo:18
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo:rw
    restart: unless-stopped
    command: odoo

  odoo-init:
    image: odoo:18
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config:/etc/odoo:rw
    command: odoo -d odoo -i all -u all --stop-after-init

volumes:
  db_data:
