name: 'odoo'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - odoo_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 3

  odoo:
    image: odoo:18
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - odoo_web_data:/var/lib/odoo:rw
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/extra-addons:rw
    restart: unless-stopped
    networks:
      - odoo_network
    command: odoo

  odoo-init:
    image: odoo:18
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - odoo_web_data:/var/lib/odoo:rw
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/extra-addons:rw
    restart: unless-stopped
    networks:
      - odoo_network
    command: odoo -d odoo -i all --stop-after-init

volumes:
  odoo_web_data:
  odoo_db_data:

networks:
  odoo_network:
    driver: bridge
