name: 'odoo'

services:
  db:
    image: postgres:18.2
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 3

  odoo:
    image: odoo:19 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/addons:rw
      # - ../enterprise-19.0:/mnt/enterprise:ro # Uncomment this line if you have the Odoo Enterprise source code and want to use it
    restart: unless-stopped
    command: odoo --addons-path=/mnt/addons,/mnt/enterprise -u=all

  odoo-init:
    image: odoo:19
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/addons:rw
      # - ../enterprise-19.0:/mnt/enterprise:ro # Uncomment this line if you have the Odoo Enterprise source code and want to use it
    restart: no
    command: odoo -d odoo --addons-path=/mnt/addons,/mnt/enterprise -i all --stop-after-init

volumes:
  db_data:
